version: '3.8'
services:
  mysql:
    image: mysql
    env_file: .env
    environment: 
      MYSQL_DATABASE: $NAME_DATABASE
      MYSQL_USER: $USER_NAME
      MYSQL_PASSWORD: $USER_PASSWORD
      MYSQL_ROOT_PASSWORD: MYSQL_RANDOM_PASSWORD
    ports: 
      - 3306:3306
    volumes: 
      - ./:/etc/mysql/data
  server:
    env_file: .env
    build: .
    networks: $BASE_DOMEN
    ports:
      - 80:8080

      
