version: '3.8'
services:
  mysql:
    image: mysql
    environment: 
      MYSQL_DATABASE: spotifyDb
      MYSQL_USER: SpotifyTgBot
      MYSQL_PASSWORD: 88003535555
      MYSQL_ROOT_PASSWORD: MYSQL_RANDOM_PASSWORD
    hostname: localhost
    ports: 
      - 3306:3306
      
